import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ClientLayout from "@/components/ClientLayout";
import FontPreload from "@/components/FontPreload";

// Configure Geist fonts with Latin subset and CSS variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap', // Ensure font display doesn't block rendering
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
});

// Metadata for SEO and social sharing
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'),
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Preload fonts for better performance */}
      <FontPreload />
      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Client-side layout with splash screen */}
        <ClientLayout>
          {/* Navigation */}
          <Navbar />
          
          {/* Main content */}
          <main className="min-h-screen">
            {children}
          </main>
          
          {/* Footer */}
          <Footer />
        </ClientLayout>
      </body>
    </html>
  );
}
